[package]
name = "json-for-redis"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "rejson"

[dependencies]
jsonpath_lib = "0.3.0"
redis-module = "1.0.1"
serde = "1.0.144"
serde_json = "1.0.85"
